# pull official base image
FROM python:3.11.3-slim-buster

# create directory for the app user
RUN mkdir -p /home/app

# create the app user
RUN addgroup --system app && adduser --system --group app

# create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PATH="${PATH}:/home/app/.local/bin"
ENV ENVIRONMENT prod
ENV TESTING 0

# install system dependencies
RUN set -eux; \
    apt-get update; \
    apt-get install --no-install-recommends netcat curl gcc make -y; \
    apt-get clean; \
    pip install --upgrade pip; \
    curl -sSL https://install.python-poetry.org | python3 -

COPY poetry.lock .
COPY pyproject.toml .

RUN poetry install --no-root --without=dev

COPY . .

# chown all the files to the app user
RUN chown -R app:app $APP_HOME

# change to the app user
USER app

CMD poetry run gunicorn --bind 0.0.0.0:8800 src.main:app -k uvicorn.workers.UvicornWorker