version: '3.8'

services:
  backend:
    build: ./
    command: bash -c "make run"
    volumes:
      - ./:/app
    ports:
      - "8800:8800"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/backend
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/backend_test
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail backend:8800/health_check || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    ports:
      - "5454:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
