version: '3.8'

services:
  backend:
    build: ./
    command: bash -c "make run"
    volumes:
      - ./:/app
    ports:
      - "8800:8800"
    environment:
      - ENVIRONMENT=dev
      - TESTING=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/backend_test
      - TOPIC=temperature/outside
    depends_on:
      db:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
    healthcheck:
      test: curl --fail backend:8800/health_check || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 5s
    restart: unless-stopped

  db:
    build:
      context: ./src/database
      dockerfile: Dockerfile
    volumes:
      - mqtt_fastapi_postgres_data:/var/lib/postgresql/data/
    ports:
      - "5454:5432"
    expose:
      - 5454
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    healthcheck:
      test: [ "CMD-SHELL", "timeout 5 mosquitto_sub -t '$$SYS/#' -C 1 | grep -v Error || exit 1" ]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s
    restart: unless-stopped

volumes:
  mqtt_fastapi_postgres_data: